spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doublehuang?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: MYSQL
server:
  port: 8081
